sudo: required
language: generic

services: -docker

before_install:
  - docker build -t 401940/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 401940/react-test npm test

after_success:
  - docker build -t 401940/multi-client ./client
  - docker build -t 401940/multi-nginx ./nginx
  - docker build -t 401940/multi-server ./server
  - docker build -t 401940/multi-worker ./worker

  #Login the docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push 401940/multi-client
  - docker push 401940/multi-nginx
  - docker push 401940/multi-server
  - docker push 401940/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-multi"
  env: "Dockermulti-env"
  bucket_name: "elasticbeanstalk-eu-central-1-125109445480"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
